pybo/models.py
from pybo import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

pybo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField
from wtforms.fields import DateField, EmailField, TelField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class UserCreateForm(FlaskForm):
    username = StringField('사용자이름', validators=[
        DataRequired(), Length(min=3, max=25)
    ])
    password1 = PasswordField('비밀번호', validators=[
        DataRequired(), EqualTo('Password2', '비밀번호가 일치하지 않습니다.')
    ])
    password2 = PasswordField('비밀번호확인', validators=[DataRequired()])
    email = EmailField('이메일', [DataRequired(), Email()])

pybo/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    #ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from .import models

    #블루프린트
    from .views import main_views, auth_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(auth_views.bp)



    return app

pybo/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm
from pybo.models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')



@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')

        return render_template('auth/signup.html', form=form)

pybo/views/main_views.py
from flask import Blueprint, render_template

bp=Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_pybo():
    return 'Hello, Pybo!'

@bp.route('/')
def index():
    return render_template('introduce.html')

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap Css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!--pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Hello, Pybo!</title>
</head>
<body>
{%include "navbar.html" %}

{% block content %}
{% endblock %}
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>


</body>
</html>

pybo/templates/introduce.html
{% extends 'base.html' %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
	<meta name="naver-site-verification" content="560c3ddbf4ca958f44be6ab765f5221cacf1f2e4"/>
		<meta property="og:image" content="https://paikdabang.com/wp-content/uploads/2022/04/빽다방_홈페이지_main_삼라봉3종.jpg">
	    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Myeongjo" rel="stylesheet">
	<link href="static/introduce.css" rel="stylesheet">
    <title>
        빽다방  :::  빽다방 소개    </title>
    <link rel='dns-prefetch' href='//s.w.org' />
		<script type="text/javascript">
			window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.4\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/2.4\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/paikdabang.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=4.9.4"}};
			!function(a,b,c){function d(a,b){var c=String.fromCharCode;l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,a),0,0);var d=k.toDataURL();l.clearRect(0,0,k.width,k.height),l.fillText(c.apply(this,b),0,0);var e=k.toDataURL();return d===e}function e(a){var b;if(!l||!l.fillText)return!1;switch(l.textBaseline="top",l.font="600 32px Arial",a){case"flag":return!(b=d([55356,56826,55356,56819],[55356,56826,8203,55356,56819]))&&(b=d([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]),!b);case"emoji":return b=d([55357,56692,8205,9792,65039],[55357,56692,8203,9792,65039]),!b}return!1}function f(a){var c=b.createElement("script");c.src=a,c.defer=c.type="text/javascript",b.getElementsByTagName("head")[0].appendChild(c)}var g,h,i,j,k=b.createElement("canvas"),l=k.getContext&&k.getContext("2d");for(j=Array("flag","emoji"),c.supports={everything:!0,everythingExceptFlag:!0},i=0;i<j.length;i++)c.supports[j[i]]=e(j[i]),c.supports.everything=c.supports.everything&&c.supports[j[i]],"flag"!==j[i]&&(c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&c.supports[j[i]]);c.supports.everythingExceptFlag=c.supports.everythingExceptFlag&&!c.supports.flag,c.DOMReady=!1,c.readyCallback=function(){c.DOMReady=!0},c.supports.everything||(h=function(){c.readyCallback()},b.addEventListener?(b.addEventListener("DOMContentLoaded",h,!1),a.addEventListener("load",h,!1)):(a.attachEvent("onload",h),b.attachEvent("onreadystatechange",function(){"complete"===b.readyState&&c.readyCallback()})),g=c.source||{},g.concatemoji?f(g.concatemoji):g.wpemoji&&g.twemoji&&(f(g.twemoji),f(g.wpemoji)))}(window,document,window._wpemojiSettings);
		</script>
		<style type="text/css">
img.wp-smiley,
img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
<link rel='stylesheet' id='klpu-front-css-css'  href='https://paikdabang.com/wp-content/plugins/kl-popup/css/klpu-front.min.css?ver=4.9.4' type='text/css' media='all' />
<link rel='stylesheet' id='insta-gallery-css'  href='https://paikdabang.com/wp-content/plugins/insta-gallery/assets/insta-gallery-min.css?ver=1.5.11' type='text/css' media='all' />
<link rel='stylesheet' id='theme-css-normalize-css'  href='https://paikdabang.com/wp-content/themes/paikdabang/assets/css/normalize.css?ver=4.9.4' type='text/css' media='all' />
<link rel='stylesheet' id='theme-css-style-css'  href='https://paikdabang.com/wp-content/themes/paikdabang/assets/css/style.css?ver=4.9.4' type='text/css' media='all' />
<link rel='stylesheet' id='theme-css-dev-style-css'  href='https://paikdabang.com/wp-content/themes/paikdabang/assets/css/style_dev.css?ver=4.9.4' type='text/css' media='all' />
<link rel='stylesheet' id='theme-css-extend-style-css'  href='https://paikdabang.com/wp-content/themes/paikdabang/assets/css/extend.a.css?ver=4.9.4' type='text/css' media='all' />
<script type='text/javascript' src='https://paikdabang.com/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='https://paikdabang.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var klpu_vars = {"ajaxurl":"https:\/\/paikdabang.com\/wp-admin\/admin-ajax.php","server_time":"1652927953"};
/* ]]> */
</script>
<script type='text/javascript' src='https://paikdabang.com/wp-content/plugins/kl-popup/js/klpu-front.min.js?ver=4.9.4'></script>
<script type='text/javascript' src='https://paikdabang.com/wp-content/themes/paikdabang/assets/js/jquery.1.12.4.min.js?ver=4.9.4'></script>
<link rel='https://api.w.org/' href='https://paikdabang.com/wp-json/' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://paikdabang.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://paikdabang.com/wp-includes/wlwmanifest.xml" />
<meta name="generator" content="WordPress 4.9.4" />

</head>
<body>

<div class="sub_section about_wrap">
    <div class="inner" style="padding-top:-65px;">
        <div class="container">


            <div class="grid_wrap intro_box" style="padding-top:-35px;">
                <h3 class="main_tit2 font-l color-1">라온 소개<br>Introduce</h3>
                <div class="m10-col-5">

                    <p class="txt">빠르게 변화하는 트렌드 속에서<br>
                    <span class="strong">대중의 이목을 사로잡을 수 있는 것은 특별함 입니다.</span>

                </div>

                    <p class="txt"><span class="strong">언제, 어디서나 쉽게 접할 수 있는 식상함은 치열한 경쟁에서 외면 받을 수밖에 없습니다.
                      라온은 고객이 원하는 바를 알고, 이를 만족시킬 특별함을 갖춘 기업으로 신선하고 이색적인 아이템과
                      독자적인 시스템을 통해 국내에서는 쉽게 접할 수 없었던 최고의 프리미엄 디저트만을 선보입니다.</span>
                    <p class="strong"><span class="strong">이러한 손님과의 소통에 라온은 손님들이 더욱 다양하게 커피를 즐길 수 있도록 노력하고 있으며 편안하게 이용하실 수 있도록 하고 있습니다.</span></p>

              <img src="http://dessert39.com/html/assets/img/brand/intro/introduction_sec_01_img.jpg">

<!--
-->
<div class="sub_section about_wrap">
    <div class="inner">
        <div class="container">

<div class="grid_wrap intro_box">
  <div class="gird_wrap intro_box.left" style="width:500px;">
      <h3 class="main_tit2 font-l color-1">수입부터 블렌딩/로스팅/신선도 유지까지 완벽한 원두</h3>
      <p class="txt">고객분들이 흔히 하는 오해 중 하나가 바로 “저렴한 커피는 퀄리티도 낮다” 입니다.<br>커피의 가격과 퀄리티의 연관성은 당연할 수 있지만, 라온은 그 선입견을 깨고자 노력하고 있습니다.</p>
      <p class="txt">라온 원두는 브라질 스페셜티 원두를 함께 블렌딩하여 사용하는데, 수확한지 1년 미만 된 아라비카 뉴크롭 생두를 생산국 정부의 수확 시기, 품질, 크기 등 엄격한 기준을 토대로 선별하여 수입합니다.<br>
           이 까다로운 조건을 통과하여 수입된 원두는 최상의 공간에서 최적의 배전도로 로스팅 되고, 로스팅이 완료된 원두는 신선도 유지를 위해 2일 내로 전국 가맹점에 빠르게 배송되며, 매장에서는 로스팅 완료 후 2주 내에 사용할 수 있게끔 엄격한 시스템이 운영되고 있습니다.</p>
      <p class="txt"><span class="strong">이렇게 만들어지는 라온 원두는 브라질 원두 고유의 묵직한 바디감과 아몬드의 고소함, 밀크초콜릿 같은 은은한 단맛이 강점입니다.</span></p>
      </div>
      <div class="grid_wrap intro_box.right">
        <img src="/static/빽다방바.jpg" alt="" style="width:500px">
      </div>

  </div>


<div class="grid_wrap intro_box">
  <div class="m10-col-5">
      <h3 class="main_tit2 font-l color-1">발 빠른 소통과 트렌드 리딩으로<br>편안한 커피 브랜드 No.1 위치 선점!</h3>
      <p class="txt">라온의 가장 큰 장점은 소비자들의 기호를 빠르게 캐치하고 시장을 리딩 하는 데에 있습니다. 매 시즌별로 해당 시즌에 유행하는 아이템을 캐치하여 대중적 선호가 높은 메뉴로 개발하고 출시합니다.<br>
          이렇게 시즌별로 트렌디한 음료를 다른 이들보다 빨리, 그리고 저렴한 가격에 맛볼 수 있다는 것은 언제나 소비자들에게 매력적인 구매 포인트가 됩니다.<br>
          <span class="strong">불편한 없이 집처럼 편안한 공간에서 커피를 즐기는 곳,<br>
          새롭고 트렌디한 음료가 언제나 나를 반겨주는 곳!<br>
          손님의 피드백을 바로 수용하는 라온<br>
          라온이 사랑받는 요인 중 하나입니다.</span>
      </p>
  </div>
                <div class="m10-col-5"><img class="fade-in-out" src="/wp-content/themes/paikdabang/assets/images/about-img5.jpg" alt=""></div>
            </div>
        </div>
    </div>
</div>

	</div><!-- .entry-content -->
</article><!-- #post-## -->	</main><!-- .site-main -->
</div><!-- .content-area -->

		</div> <!-- END #content-wrap -->
</div>




{% endblock %}

</body>
</html>

pybo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">라온</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            메뉴
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            커뮤니티
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            고객의 소리
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>

      </ul>
      <form class="d-flex">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('auth.signup') }}">계정생성</a>
        </li>
            <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">로그인</a>
        </li>
          </ul>
      </form>
    </div>
  </div>
</nav>